---
title: Persistence and Change in Attitudes Toward Unification with North Korea

# Use letters for affiliations
author:
  - name: Jaeyoung Hur
    affiliation: a
address:
  - code: a
    address: Global leaders College, Yonsei University, Seoul, ROK
    
# Optional: line of arbitrary text with additional information.
# Could be used, for example, to mention the bibliographic info in a post-print.
# If not specified, defaults to "This version was compiled on \today"
#date_subtitle: Published in *Journal of Statistical Software*, 2018

# For footer text  TODO(fold into template, allow free form two-authors)
lead_author_surname: Jaeyoung Hur
header-includes:
  - \usepackage{ntheorem}
  - \theoremseparator{:}
  - \newtheorem{hyp}{Hypothesis}
# Place eg a DOI URL or CRAN Package URL here
#doi_footer: ""

# Abstract
#abstract: |
#  This article examines whether existing explanations of South Korean attitudes regarding North Korea and Korean unification adequately explain changes after the declaration at Panmunjom on April 27, 2018. This study uses the National Consciousness Survey Data to estimate these shifts in attitude. Our results show that South Korean attitudes shifted following the Panmunjom Declaration for Peace, Prosperity, and Unification of the Korean Peninsula. We show that existing explanations for generational effects do not explain the national attitude shifts on unification; our study demonstrates that a wide divergence exists between younger and the older generations, and younger generations are more likely to display a negative attitude toward North Korea and unification even after the Declaration. We also show that the prospects of unification evoke different attitudes across generations. Our results imply that the Panmunjom Declaration is a prominent political event, but it is necessary to analyze it without overestimating it.  

# Optional: Acknowledgements
#acknowledgements: |
#  This template package builds upon, and extends, the work of the excellent
#  [rticles](https://cran.r-project.org/package=rticles) package, and both packages rely on the
#  [PNAS LaTeX](http://www.pnas.org/site/authors/latex.xhtml) macros. Both these sources are
#  gratefully acknowledged as this work would not have been possible without them.  Our extensions
#  are under the same respective licensing term
#  ([GPL-3](https://www.gnu.org/licenses/gpl-3.0.en.html) and
#  [LPPL (>= 1.3)](https://www.latex-project.org/lppl/)).

# Optional: One or more keywords
#keywords:
#  - The Panmunjom Declaration
#  - Attitudes on Korean Unification
#  - Attitudes toward North Korea
#  - Generations
#  - Prospects of unification

# Paper size for the document, values of letter and a4
papersize: letter

# Font size of the document, values of 9pt (default), 10pt, 11pt and 12pt
fontsize: 10pt

# Optional: Force one-column layout, default is two-column
#one_column: true

# Optional: Enables lineno mode, but only if one_column mode is also true
#lineno: true

# Optional: Enable one-sided layout, default is two-sided
#one_sided: true

# Optional: Enable section numbering, default is unnumbered
#numbersections: false

# Optional: Specify the depth of section number, default is 5
#secnumdepth: 0

# Optional: Skip inserting final break between acknowledgements, default is false
skip_final_break: true

# Optional: Bibliography 
bibliography: parkhur2020

# Optional: Enable a 'Draft' watermark on the document
#watermark: true

# Customize footer, eg by referencing the vignette
footer_contents: "Presentation Script"

# Produce a pinp document
output: pinp::pinp

# Required: Vignette metadata for inclusion in a package.
vignette: >
  %\VignetteIndexEntry{YourPackage-vignetteentry}
  %\VignetteKeywords{YourPackage, r, anotherkeyword}
  %\VignettePackage{YourPackage}
  %\VignetteEngine{knitr::rmarkdown}
---

## Motivations and Research Questions

The inter-Korean relationship faced several historical events in 2018. After the new administration pursues cooperative policies with North Korea, North Korea sent athletes to the Pyeongchang Winter Olympics. It seems a signal that South Korea and North Korea enter into the new state of their relationship. Also, the two Korea's leaders meet at Panmunjom to declare peace, prosperity, and unification.

The dramatic changes in the Inter-Korean relationship made South Koreans expect a 'better future.' however, we need to remind that the inter-Korean relationship has varied by different administrations. Although Moon Jae-in administration turned to the N.K. cooperative stance, whether it will succeed, is not guaranteed.

Existing studies explain the impacts of 'historical events' between North and South Koreas. However, Koreans have experiences inconsistent policies and N.K.'s Intermittent provocation. Here, we ask whether the 4.27 Panmunjom declaration leads to fundamental changes for the inter-Korean relationship. In particular, we examine whether South Koreans' attitudes and perceptions toward North Korea and unification have changed.

## Literature Reviews

Previous studies present various factors that are expected to affect the attitudes toward North Korea and Unification. For a long time, the nationalism-based legitimacy of unification explained why we "should" pursue the unification. However, as the time of division lasts, political factors or cost-benefits approaches emerge to explain South Koreans' attitudes. Some scholars also argue that a group of people who have similar experiences will show similar attitudes, and those attitudes might vary across the groups (generations). Although previous literature has provided various explanations, they do not consider the possible impact outside, such as external events. In the inter-Korean relationship, we have observed several "unexpected" political events that drastically shift the inter-Korean relationship. 

Some people expect the Panmunjom Declaration will change the inter-Korean relationship. In fact, various media suggested that the Korean peninsula prospect would be better, and after the declaration, President Moon's approval exceeded 80%.

However, does the declaration bring fundamental changes to us as we expected? South Koreans have experienced varying policy cycles by different administrations. Conservative administrations tended to take a strong stance against North Korea, while liberal administrations led the engagement policy as a basis for reconciliation and cooperation. It means that members of South Korea have already experienced a similar type of event and its failure.

## Research Design

We examine the changes in attitudes toward North Korea. We expect that generations mainly experienced tensions and conflicts between South and North for a long time are more likely to show more negative attitudes toward North Korea and unification. Otherwise, generations under cooperative moods between South and North can expect an improvement of inter-Korean relationships. Thus, we draw the first hypothesis as follows:

\begin{hyp}\label{hyp1} The younger generation show more negative attitudes toward North Korea than other generations, even after the Panmunjom Declaration. \end{hyp}

Next, we also examine the changes in attitudes toward unification. According to recent studies, the cost and benefits of unification are dominant explanations to justify unification. However, the utilities of unification can vary depending on the conditions.

When we state the Panmunjom Declaration is a positive signal about unification prospects, the respondents will show different attitudes conditional on the varying prospects. The second hypothesis of this project as follows: 

\begin{hyp}\label{hyp2} The prospects for unification affect the need for unification differently across generations. \end{hyp}

In particular, we expect that the more positive prospects one expects, the more likely, the older generations will favor unification. However, we also expect that even the more positive prospects they expect, the younger generations are less likely to support unification.

### Data

Our sample is from the KBS National unification consciousness survey of 2018. It is surveyed from August 3rd to 7th in 2018. The size of the sample is 1,000 over the age of 19. We think the sample is the most relevant to examine the research question due to the least time difference from the Panmunjom Declaration.

### Dependent variable

#### Attitudes toward North Korea: Leadership and General State

The first dependent variable is the attitudes toward North Korea. We have two indicators to show it. The first is the attitudes toward North Korean leadership, and the second is the attitudes toward general North Korea as a state.

When we looked at the distribution of attitudes toward North Korea after the Panmunjom Declaration, we can see a difference between the attitudes toward North Korean leadership and North Korea in general. The data shows that after the Panmunjom Declaration, respondents are still dissatisfied with the North Korean leadership. At the same time, however, respondents perceive North Korea as an inevitable entity to interact to solve the inter-Korean relationship and other problems concerning the Korean peninsula.


#### Attitudes toward Unification
 
The second dependent variable is the attitudes toward unification. The most frequent response is that respondents prefer unification if it creates no burdens (45.5%). Only 8.9% of respondents say that they do not prefer unification. A quarter of the respondents answer that they prefer the status quo (25.2%), and only 20.4% say they prefer unification unconditionally.

### Key explanatory variables and controls

One of the main explanatory variables in this study is generational. We investigate how the generations are associated with the attitudes toward North Korea and unification after the Panmunjom Declaration. Generations are categorical variables measured in 10-year units based on age.

The other explanatory variable of interest is the prospect of unification. The longer the period of unification, the more negative the prospect. We coded that the most negative prospect as 1, and the most positive prospect as 6.

Finally, we control for other variables that can potentially affect the attitudes toward North Korea and unification. The variables include the regions where respondents live, gender, education level, income level, evaluations of North Korea policies under the Jae-In Moon administration, all drawn from the KBS survey data.

### Methods

As the dependent variable is ordered and discrete, we use the ordered logistic regression model. However, as the coefficients of ordered logistic regression is not intuitive to understand the results, we will present the first differences in predicted probabilities and predicted probabilities of key explanatory variables' effects.

## Empirical Findings

### Model for the hypothesis \ref{hyp1}
The first model is about attitudes toward North Korea after the Panmunjom Declaration.
As the general N.K. attitudes show no significant differences across the generations. Here, we present the model of attitudes toward North Korean leadership.

The 40s and the 50s show statistically significant differences compared to the 20s. It means that the 40s and the 50s are more likely to favor North Korean leadership than the 20s.

The plot of the first differences in predicted probabilities shows that the 40s and the 50s are more likely to be satisfied with the North Korean leadership while they are less likely to be dissatisfied with the North Korean leadership.

### Model for the hypothesis \ref{hyp2}

Next, the second model shows how the attitudes toward unification by different generations are conditional on unification prospects. The results show that the 50s and 60s are more likely to be favorable toward unification than the 20s. The 30s and 40s are not significantly different from the 20s.

We estimate the predicted probabilities of each generation group that how their choices of the unification are conditional on unification prospects. The plot of the 50s and 60s shows that as the prospects become positive, they are less likely to choose "not preferred" and "Status quo." Otherwise, as the prospects become positive, they are more likely to support unification.

Then, how about the 20s, 30s, and 60+? Interestingly, the trends are not so different in the predicted probabilities. The only difference can be seen at the panel of "preferred without burdens." The 20s, 30s, and 40s show more significant variations in the predicted probabilities as unification prospects vary.

## Conclusion and Implications

kaaks



